version: '3.9'

services:
  # ----------------------------
  # Aplicación Node.js
  # ----------------------------
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - "3000:3000"
    networks:
      - devnet

  # ----------------------------
  # Jenkins con Docker CLI
  # ----------------------------
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins
    user: root
    restart: always
    ports:
      - "8080:8080"
    environment:
      DOCKER_HOST: tcp://docker:2375
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # permite usar Docker del host
      - $HOME/.docker:/var/jenkins_home/.docker:ro  # opcional: acceso a credenciales Docker Hub
    networks:
      - devnet

  # ----------------------------
  # Nexus Repository
  # ----------------------------
  nexus:
    image: sonatype/nexus3
    container_name: nexus_repo
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - devnet

  # ----------------------------
  # SonarQube
  # ----------------------------
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db_sonar:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    ports:
      - "8084:9000"
    depends_on:
      - db_sonar
    networks:
      - devnet

  # ----------------------------
  # Base de datos de SonarQube
  # ----------------------------
  db_sonar:
    image: postgres:15
    container_name: db_sonar
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - devnet

# ----------------------------
# Red externa
# ----------------------------
networks:
  devnet:
    external: true

# ----------------------------
# Volúmenes persistentes
# ----------------------------
volumes:
  jenkins_home:
  nexus-data:
  postgresql:
